export interface Reminder {
  id?: string        // auto-generated by Firebase
  title: string      // e.g., "Water Plant"
  description?: string // optional details
  date: Date       // YYYY-MM-DD or ISO date string
  done?: boolean     // whether reminder is completed
  userId?: string    // link to Firebase Auth user
  plantId?:  string   // link to the plant
}
